export { default as BookmarkIcon } from '@mui/icons-material/Bookmark';
export { default as BookmarkBorderIcon } from '@mui/icons-material/BookmarkBorder';
export { default as SearchIcon } from '@mui/icons-material/Search';
export { default as FormatBoldIcon } from '@mui/icons-material/FormatBold';
export { default as FormatItalicIcon } from '@mui/icons-material/FormatItalic';
export { default as StrikeThroughSIcon } from '@mui/icons-material/StrikethroughS';
export { default as CodeIcon } from '@mui/icons-material/Code';
export { default as FileIcon } from '@mui/icons-material/Description';
export { default as SendIcon } from '@mui/icons-material/Send';
