openapi: 3.0.0
info:
  title: MyMemoApp
  description: メモアプリのサーバーAPIです。
  version: 1.0.0

servers:
  - description: 開発サーバー
    url: http://localhost:3000/api/

tags:
  - name: Memos
    description: メモに関する API群です。

paths:
  /memos/search:
    get:
      operationId: memosSearchGET
      summary: 検索文字列で検索したメモを登録日時でソートして返します。
      parameters:
        - in: query
          name: SearchQuery
          description: 検索文字列
          schema:
            $ref: '#/components/schemas/SearchQuery'
      responses:
        "200":
          description: 検索文字列で検索したメモを登録日時でソートして返します。
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Memo'
      tags:
        - Memos

  /memos/create:
    post:
      operationId: memosCreatePOST
      summary: メモを登録します。
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MemoCreateProps'
      responses:
        "200":
          description: 登録されたメモを返します。
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Memo'
      tags:
        - Memos

  /memos/update:
    put:
      operationId: memosUpdatePOST
      summary: メモを更新します。
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Memo'
      responses:
        "200":
          description: 更新されたメモを返します。
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Memo'
      tags:
        - Memos

  /memos/delete:
    delete:
      operationId: memosDeletePOST
      summary: メモを削除します。
      parameters:
        - in: query
          name: memoId
          description: 削除対象のメモID
          required: true
          schema:
            $ref: '#/components/schemas/memoId'
      responses:
        "200":
          description: IDで指定されたメモを削除します。
      tags:
        - Memos

components:
  schemas:
    Memo:
      description: メモオブジェクト
      type: object
      properties:
        id:
          type: integer
          description: ID
        content:
          type: string
          description: コンテンツ
        createdDate:
          type: string
          description: 登録日付
          pattern: '^([1-9]|1[0-2])月([1-9]|[12][0-9]|3[01])日\((月|火|水|木|金|土|日)\)$'
          example: "12月31日(日)"
        createdTime:
          type: string
          description: 登録時刻
          pattern: '^([01][0-9]|2[0-3]):[0-5][0-9]$'
          example: "00:59"
        bookmarkFlag:
          type: boolean
          description: ブックマークフラグ
          default: false
        updatedDatetime:
          type: string
          description: 更新日時
          pattern: '^([1-9]|1[0-2])月([1-9]|[12][0-9]|3[01])日\((月|火|水|木|金|土|日)\) ([01][0-9]|2[0-3]):[0-5][0-9]$'
          example: "12月31日(日) 00:59"
      required:
        - id
        - content
        - createdDate
        - createdTime
        - bookmarkFlag

    MemoCreateProps:
      type: object
      properties:
        content:
          description: 投稿内容
          type: string
      required:
        - content

    memoId:
      description: メモID
      type: integer

    SearchQuery:
      type: object
      properties:
        keywords:
          type: string
          description: 検索文字列
        bookmarkSearch:
          type: boolean
          description: ブックマーク検索フラグ
          default: false
      required:
        - keywords
        - bookmarkSearch
