openapi: 3.0.0
info:
  title: MyMemoApp
  description: メモアプリのサーバーAPIです。
  version: 1.0.0
servers:
  - description: 開発サーバー
    url: http://localhost:3000/api/
tags:
  - name: Memos
    description: メモに関する API群です。
paths:
  /memos/all:
    get:
      operationId: memosAllGET
      summary: 登録されているメモを登録日時でソートして返します。
      responses:
        "200":
          description: 登録されているメモを登録日時でソートして返します。
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Memo'
      tags:
        - Memos
  /memos/find:
    get:
      operationId: memosFindGET
      summary: IDで指定されたメモを返します。
      parameters:
        - in: query
          name: memoId
          description: 取得対象のメモID
          required: true
          schema:
            $ref: '#/components/schemas/memoId'
      responses:
        "200":
          description: IDで指定されたメモを返します。
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Memo'
      tags:
        - Memos
  /memos/search:
    get:
      operationId: memosSearchGET
      summary: 検索文字列で検索したメモを登録日時でソートして返します。
      parameters:
        - in: query
          name: searchQuery
          description: 検索文字列
          required: true
          examples:
            string1:
              summary: 検索文字列1
              value: 文字列1
            string2:
              summary: 検索文字列2
              description: スペースで区切り文字列を検索します。
              value: 文字列1 文字列2
          schema:
            $ref: '#/components/schemas/searchQuery'
      responses:
        "200":
          description: 検索文字列で検索したメモを登録日時でソートして返します。
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Memo'
      tags:
        - Memos
  /memos/create:
    post:
      operationId: memosCreatePOST
      summary: メモを登録します。
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MemoCreateProps'
      responses:
        "200":
          description: 登録されたメモを返します。
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Memo'
      tags:
        - Memos
  /memos/update:
    put:
      operationId: memosUpdatePOST
      summary: メモを更新します。
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Memo'
      responses:
        "200":
          description: 更新されたメモを返します。
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Memo'
      tags:
        - Memos
  /memos/delete:
    delete:
      operationId: memosDeletePOST
      summary: IDで指定されたメモを削除します。
      parameters:
        - in: query
          name: memoId
          description: 削除対象のメモID
          required: true
          schema:
            $ref: '#/components/schemas/memoId'
      responses:
        "200":
          description: IDで指定されたメモを返します。
      tags:
        - Memos
components:
  schemas:
    memoId:
      description: メモ識別子
      type: integer

    searchQuery:
      description: 検索クエリ
      type: string

    MemoCreateProps:
      type: object
      properties:
        content:
          description: 投稿内容
          type: string
      required:
        - content

    Memo:
      description: メモオブジェクト
      type: object
      allOf:
        - type: object
          properties:
            id:
              description: ID
              type: integer
            createdAt:
              description: 登録日時(UTC)
              type: string
              format: date-time
            updatedAt:
              description: 登録日時(UTC)
              type: string
              format: date-time
            isBookmarked:
              description: ブックマークフラグ
              type: boolean
              default: false
          required:
            - id
            - createdAt
            - updatedAt
            - isBookmarked
        - $ref: '#/components/schemas/MemoCreateProps'
